server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/finance}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  jwt:
    secret: ${JWT_SECRET:change-this-in-prod}
    expirationMs: 2592000000 # 30 days

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
